// Seeds the 104 matches of the Mundial 2026.
// Matches.json is generated by `node prisma/data/generate-matches.mjs`.
// homeTeamId/awayTeamId stay null until the official draw — labels are used
// in the meantime ("Eq A1", "Ganador R32 1", etc.).
//
// Run:  npx tsx prisma/seed-matches.ts

import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '../generated/prisma/client.js';
import matches from './data/matches.json' with { type: 'json' };

type SeedMatch = {
  matchNumber: number;
  phase:
    | 'GROUPS'
    | 'ROUND_32'
    | 'ROUND_16'
    | 'QUARTERS'
    | 'SEMIS'
    | 'THIRD_PLACE'
    | 'FINAL';
  groupCode: string | null;
  homeTeamLabel: string;
  awayTeamLabel: string;
  kickoffAt: string;
  predictionsLockAt: string;
  venue: string;
  city: string;
  country: string;
};

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

async function main() {
  let inserted = 0;
  let updated = 0;

  for (const m of matches as SeedMatch[]) {
    const existing = await prisma.match.findUnique({ where: { matchNumber: m.matchNumber } });
    const data = {
      phase: m.phase,
      groupCode: m.groupCode,
      homeTeamLabel: m.homeTeamLabel,
      awayTeamLabel: m.awayTeamLabel,
      kickoffAt: new Date(m.kickoffAt),
      predictionsLockAt: new Date(m.predictionsLockAt),
      venue: m.venue,
      city: m.city,
      country: m.country,
    };
    await prisma.match.upsert({
      where: { matchNumber: m.matchNumber },
      update: data,
      create: { matchNumber: m.matchNumber, ...data },
    });
    if (existing) updated++;
    else inserted++;
  }

  // eslint-disable-next-line no-console
  console.log(
    `Seeded ${matches.length} matches (${inserted} inserted, ${updated} updated)`,
  );
}

main()
  .catch((err) => {
    // eslint-disable-next-line no-console
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
