import type { Metadata, Viewport } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/providers/query-provider";
import { AuthProvider } from "@/providers/auth-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/ui/toaster";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-noto-sans",
  weight: ["400", "500", "700"],
  display: "swap",
});

// TODO: Cuando el cliente provea `public/fonts/FWC2026-CondensedBlack.woff2`
// (proprietario de FIFA), reemplazar este bloque por:
//
//   import localFont from "next/font/local";
//   const fwc = localFont({
//     src: "../public/fonts/FWC2026-CondensedBlack.woff2",
//     variable: "--font-fwc",
//     weight: "900",
//     display: "swap",
//   });
//
// Y agregar `${fwc.variable}` a la className del <html>.
//
// Mientras tanto definimos la CSS variable con un fallback de sistema
// (Arial Narrow Black), para que `--font-display` siga funcionando.
const fwcFallbackVariable = {
  variable: "--font-fwc",
  className: "fwc-fallback",
};

export const metadata: Metadata = {
  title: "Prode Mundial 2026 — Tiro Federal",
  description:
    "Pronósticos del Mundial de Fútbol 2026 — Club Tiro Federal de Bahía Blanca",
  manifest: "/manifest.json",
  applicationName: "Prode Mundial 2026",
  appleWebApp: {
    capable: true,
    title: "Prode",
    statusBarStyle: "black-translucent",
  },
  icons: {
    icon: [
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  // TODO: replace these placeholder PNGs (solid #05090e squares generated by
  // scripts/gen-pwa-icons.mjs) with real artwork featuring the Tiro Federal
  // crest before the production launch.
};

export const viewport: Viewport = {
  themeColor: "#05090e",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es-AR"
      className={`${notoSans.variable} ${fwcFallbackVariable.className} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          <QueryProvider>
            <AuthProvider>{children}</AuthProvider>
          </QueryProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
